import { useState } from 'react';
import { useSessionStore } from '../store/session.store';
import StreamView from './StreamView';
import MessagesView from './MessagesView';
import LogsView from './LogsView';
import ScreenshotsView from './ScreenshotsView';
import { createWhatsAppContact } from '../api/contacts.api';

export default function MainPanel() {
  const [activeTab, setActiveTab] = useState<'stream' | 'messages' | 'screenshots' | 'logs'>('stream');
  const { sessions, selectedSessionId } = useSessionStore();
  const [isCreatingContact, setIsCreatingContact] = useState(false);

  const selectedSession = sessions.find((s) => s.id === selectedSessionId);

  const handleCreateContact = async () => {
    if (!selectedSession) return;
    
    setIsCreatingContact(true);
    try {
      await createWhatsAppContact({
        sessionId: selectedSession.id,
        phoneNumber: '544463186',
        // firstName and lastName will be randomly generated by the backend
      });
      alert('✅ Contact créé avec succès !');
    } catch (error: any) {
      console.error('Failed to create contact:', error);
      alert('❌ Échec de la création du contact: ' + (error.response?.data?.details || error.message));
    } finally {
      setIsCreatingContact(false);
    }
  };

  if (!selectedSession) {
    return (
      <div className="flex-1 flex items-center justify-center bg-gray-50">
        <div className="text-center text-gray-500">
          <svg
            className="w-24 h-24 mx-auto mb-4 text-gray-300"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
            />
          </svg>
          <h2 className="text-xl font-semibold mb-2">No Session Selected</h2>
          <p>Select a session from the sidebar to view details</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 p-4">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-lg font-semibold">{selectedSession.phone}</h2>
            <p className="text-sm text-gray-600">
              State: {selectedSession.state} • {selectedSession.isActive ? 'Active' : 'Inactive'}
            </p>
          </div>
          <div className="flex gap-2">
            {selectedSession.linkedWeb && (
              <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm">
                Linked to Web
              </span>
            )}
            {selectedSession.isActive && (
              <button
                onClick={handleCreateContact}
                disabled={isCreatingContact}
                className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                  isCreatingContact
                    ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                    : 'bg-whatsapp-green text-white hover:bg-green-600'
                }`}
              >
                {isCreatingContact ? '⏳ Creating...' : '➕ Create Contact'}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="bg-white border-b border-gray-200">
        <div className="flex">
          <button
            onClick={() => setActiveTab('stream')}
            className={`px-6 py-3 font-medium transition-colors ${
              activeTab === 'stream'
                ? 'text-whatsapp-green border-b-2 border-whatsapp-green'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Stream View
          </button>
          <button
            onClick={() => setActiveTab('messages')}
            className={`px-6 py-3 font-medium transition-colors ${
              activeTab === 'messages'
                ? 'text-whatsapp-green border-b-2 border-whatsapp-green'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Messages
          </button>
          <button
            onClick={() => setActiveTab('screenshots')}
            className={`px-6 py-3 font-medium transition-colors ${
              activeTab === 'screenshots'
                ? 'text-whatsapp-green border-b-2 border-whatsapp-green'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Screenshots
          </button>
          <button
            onClick={() => setActiveTab('logs')}
            className={`px-6 py-3 font-medium transition-colors ${
              activeTab === 'logs'
                ? 'text-whatsapp-green border-b-2 border-whatsapp-green'
                : 'text-gray-600 hover:text-gray-900'
            }`}
          >
            Logs
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-hidden">
        {activeTab === 'stream' && <StreamView session={selectedSession} />}
        {activeTab === 'messages' && <MessagesView session={selectedSession} />}
        {activeTab === 'screenshots' && <ScreenshotsView session={selectedSession} />}
        {activeTab === 'logs' && <LogsView session={selectedSession} />}
      </div>
    </div>
  );
}






