-- AlterEnum: Add new states to ProvisionState
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'LAUNCHING_WHATSAPP';
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'ENTERING_PHONE';
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'SETTING_UP_PROFILE';

