-- AlterEnum: Add new provision states
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'COMPLETING_PROFILE';
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'TESTING_DEEPLINK';
ALTER TYPE "ProvisionState" ADD VALUE IF NOT EXISTS 'CREATING_SNAPSHOT';

